# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fengur
author: Fengur
author_link: http://fengur.cn
author_description: Easy life easy mind 
email: duraedream@gmail.com
description: Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fengur.cn" # the base hostname & protocol for your site
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
# 评论系统（Disqus）
disqus:
  shortname: fengur-demo # 你可以在 Disqus 注册后替换为自己的 shortname
# 主题相关配置
minimal_mistakes_skin: "default"
# 导航栏示例
nav:
  - title: "首页"
    url: "/"
  - title: "归档"
    url: "/year-archive/"
  - title: "关于"
    url: "/about/"
# 其他配置可参考官方文档

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
